### ISSUE TITLE
Koan Module 07: Test Summary (Question/Feedback)

### ISSUE THREAD

**Issue by meeech** [circleci/CircleCI-Training-Koans#32]
In koan 07, in the config, there is this line: 
```
# Add below this line, do not modify above
```
But the `name` argument is invalid for `build-tools/test-results` step. 

I'll submit pr, but not sure what the intent here is.  

Also, the referenced orb is older - this orb seems to be at 3.0 now - I can't find the referenced one (2.2.0) in https://github.com/circleci-public/build-tools-orb tags. 

Also not clear: is _test summary_ tab still a thing in the UI?

I'll just work by bumping it up to 3.0 in my koan.

**Comment by felixshiftellecon** [comment]
Thanks for taking the time to update this koan!

> Also not clear: is _test summary_ tab still a thing in the UI?

Yes, this is still available and can be found by clicking into a job and navigating to the Tests tab.

![Screen Shot 2022-03-11 at 10 08 57 AM](https://user-images.githubusercontent.com/57482070/157893980-676acbce-3667-4b97-9d98-d382c845abf4.png)

**Comment by meeech** [comment]
thanks!
